# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-02 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
