# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-07 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_itemmodel_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='rating',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
